booking.property= Booking Profile Dev Updated

# Configuración de base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/bookingdb
spring.datasource.username=arlintonar
spring.datasource.password=MyPasword123
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA/Hibernate (opcional para creación automática de tablas)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


