booking.property= Booking Profile Dev


# JPA/Hibernate (opcional para creación automática de tablas)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true